import type { DesignSystemWorkspaceData, FindingDecision, PreviewCacheEntry, RuntimeComponentRelationship, UserComponentFixture } from '@shared/types/designSystem'
import { getDesignSystemWorkspaceFile } from '../paths'
import { readJsonFile, writeJsonFileAtomic } from '../atomicJson'

const empty = (projectId: string): DesignSystemWorkspaceData => ({ schemaVersion: 1, projectId, fixtures: [], previewCache: [], runtimeRelationships: [], findingDecisions: [], approvedObservationIds: [], patternClassifications: {}, updatedAt: new Date().toISOString() })
export function getData(userDataPath: string, projectId: string): DesignSystemWorkspaceData {
  const stored = readJsonFile<Partial<DesignSystemWorkspaceData>>(getDesignSystemWorkspaceFile(userDataPath, projectId), {})
  return { ...empty(projectId), ...stored, schemaVersion: 1, projectId, fixtures: stored.fixtures ?? [], previewCache: stored.previewCache ?? [], runtimeRelationships: stored.runtimeRelationships ?? [], findingDecisions: stored.findingDecisions ?? [], approvedObservationIds: stored.approvedObservationIds ?? [], patternClassifications: stored.patternClassifications ?? {} }
}
function save(userDataPath: string, data: DesignSystemWorkspaceData) { const value = { ...data, updatedAt: new Date().toISOString() }; writeJsonFileAtomic(getDesignSystemWorkspaceFile(userDataPath, data.projectId), value); return value }
export function saveFixture(userDataPath: string, projectId: string, fixture: UserComponentFixture) { const data = getData(userDataPath, projectId); const fixtures = [...data.fixtures.filter((item) => item.id !== fixture.id), { ...fixture, projectId, origin: 'user-defined' as const, updatedAt: new Date().toISOString() }]; return save(userDataPath, { ...data, fixtures }).fixtures.find((item) => item.id === fixture.id)! }
export function deleteFixture(userDataPath: string, projectId: string, fixtureId: string) { const data = getData(userDataPath, projectId); save(userDataPath, { ...data, fixtures: data.fixtures.filter((item) => item.id !== fixtureId), previewCache: data.previewCache.filter((item) => item.fixtureId !== fixtureId) }) }
export function savePreviewCache(userDataPath: string, projectId: string, entry: PreviewCacheEntry) { const data = getData(userDataPath, projectId); const previewCache = [...data.previewCache.filter((item) => !(item.componentId === entry.componentId && item.fixtureId === entry.fixtureId)), entry]; save(userDataPath, { ...data, previewCache }); return entry }
export function saveRuntimeRelationships(userDataPath: string, projectId: string, componentId: string, relationships: RuntimeComponentRelationship[]) { const data = getData(userDataPath, projectId); save(userDataPath, { ...data, runtimeRelationships: [...data.runtimeRelationships.filter((item) => item.componentId !== componentId), ...relationships] }); return relationships }
export function saveFindingDecision(userDataPath: string, projectId: string, decision: FindingDecision) { const data = getData(userDataPath, projectId); const findingDecisions = [...data.findingDecisions.filter((item) => item.findingId !== decision.findingId), { ...decision, updatedAt: new Date().toISOString() }]; return save(userDataPath, { ...data, findingDecisions }).findingDecisions.find((item) => item.findingId === decision.findingId)! }
export function setObservationApproved(userDataPath: string, projectId: string, observationId: string, approved: boolean) { const data = getData(userDataPath, projectId); const ids = approved ? [...new Set([...data.approvedObservationIds, observationId])] : data.approvedObservationIds.filter((id) => id !== observationId); return save(userDataPath, { ...data, approvedObservationIds: ids }) }
