const fs = require('fs')
const path = require('path')

// Keep this surface deliberately finite. These are PHP_INI_ALL/PERDIR values
// that are useful during local development and safe to carry between the
// managed PHP versions Stacker supports.
const PHP_CONFIG_FIELDS = [
  { key: 'memory_limit', label: 'Memory limit', type: 'size', placeholder: '128M' },
  { key: 'max_execution_time', label: 'Maximum execution time', type: 'integer', min: 0, max: 86400, placeholder: '30' },
  { key: 'max_input_time', label: 'Maximum input time', type: 'integer', min: -1, max: 86400, placeholder: '60' },
  { key: 'post_max_size', label: 'Maximum POST size', type: 'size', placeholder: '8M' },
  { key: 'upload_max_filesize', label: 'Maximum upload size', type: 'size', placeholder: '2M' },
  { key: 'max_file_uploads', label: 'Maximum file uploads', type: 'integer', min: 1, max: 1000, placeholder: '20' },
  { key: 'display_errors', label: 'Display errors', type: 'boolean' },
  { key: 'display_startup_errors', label: 'Display startup errors', type: 'boolean' },
  { key: 'error_reporting', label: 'Error reporting', type: 'error-level', placeholder: 'E_ALL' },
  { key: 'date.timezone', label: 'Default timezone', type: 'timezone', placeholder: 'UTC' },
]

const FIELD_BY_KEY = new Map(PHP_CONFIG_FIELDS.map(field => [field.key, field]))
const SIZE_PATTERN = /^-?1$|^\d+(?:\.\d+)?[KMG]?$/i
const TIMEZONE_PATTERN = /^(?:UTC|[A-Za-z_]+(?:\/[A-Za-z0-9_+.-]+)+)$/
const ERROR_LEVEL_PATTERN = /^[A-Z0-9_|&~() ]+$/

function validatePhpConfig(input) {
  if (input == null) return {}
  if (typeof input !== 'object' || Array.isArray(input)) throw new Error('PHP configuration must be an object.')
  const result = {}
  for (const [key, rawValue] of Object.entries(input)) {
    const field = FIELD_BY_KEY.get(key)
    if (!field) throw new Error(`Unsupported PHP setting: ${key}.`)
    if (rawValue === '' || rawValue == null) continue
    if (field.type === 'boolean') {
      if (typeof rawValue !== 'boolean') throw new Error(`${field.label} must be on or off.`)
      result[key] = rawValue
      continue
    }
    const value = String(rawValue).trim()
    if (/\r|\n|[";]/.test(value)) throw new Error(`${field.label} contains unsupported characters.`)
    if (field.type === 'integer') {
      const number = Number(value)
      if (!Number.isInteger(number) || number < field.min || number > field.max) throw new Error(`${field.label} must be a whole number between ${field.min} and ${field.max}.`)
    } else if (field.type === 'size' && !SIZE_PATTERN.test(value)) throw new Error(`${field.label} must be a number with an optional K, M, or G suffix.`)
    else if (field.type === 'timezone' && !TIMEZONE_PATTERN.test(value)) throw new Error(`${field.label} must be a PHP timezone such as UTC or Africa/Johannesburg.`)
    else if (field.type === 'error-level' && !ERROR_LEVEL_PATTERN.test(value)) throw new Error(`${field.label} must be a PHP error-level expression such as E_ALL or E_ALL & ~E_DEPRECATED.`)
    result[key] = value
  }
  return result
}

function serializePhpConfig(input) {
  const values = validatePhpConfig(input)
  const lines = ['; Generated by Stacker. Changes are replaced when project settings are saved.']
  for (const field of PHP_CONFIG_FIELDS) {
    if (!(field.key in values)) continue
    const value = typeof values[field.key] === 'boolean' ? (values[field.key] ? 'On' : 'Off') : values[field.key]
    lines.push(`${field.key} = ${value}`)
  }
  return `${lines.join('\n')}\n`
}

function safeProjectId(projectId) {
  const value = String(projectId || '')
  if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error('Invalid project identifier for PHP configuration.')
  return value
}

class PhpConfigManager {
  constructor(root) { this.root = root }

  directoryFor(project) { return path.join(this.root, safeProjectId(project.id)) }

  sync(project) {
    const values = validatePhpConfig(project.phpConfig)
    const directory = this.directoryFor(project)
    const target = path.join(directory, '99-stacker-project.ini')
    if (!Object.keys(values).length) {
      fs.rmSync(directory, { recursive: true, force: true })
      return null
    }
    fs.mkdirSync(directory, { recursive: true })
    const temporary = `${target}.${process.pid}.tmp`
    fs.writeFileSync(temporary, serializePhpConfig(values), { mode: 0o600 })
    fs.renameSync(temporary, target)
    return { directory, path: target, values }
  }

  environmentFor(project, baseEnvironment = process.env) {
    const config = this.sync(project)
    // A trailing delimiter preserves PHP's compile-time scan directory while
    // adding Stacker's project-specific fragment. If the launching shell has
    // an explicit scan path, retain it after Stacker's higher-priority path.
    return config ? { PHP_INI_SCAN_DIR: `${config.directory}${path.delimiter}${baseEnvironment.PHP_INI_SCAN_DIR || ''}` } : {}
  }

  remove(projectId) {
    fs.rmSync(path.join(this.root, safeProjectId(projectId)), { recursive: true, force: true })
  }
}

module.exports = { PhpConfigManager, PHP_CONFIG_FIELDS, validatePhpConfig, serializePhpConfig }
