import { useEffect, useMemo, useState } from 'react'
import type { FeatureHandoff } from '@shared/types/handoff'
import type { HandoffInput } from '@shared/types/handoff'
import type { Breakpoint } from '@shared/types/designNode'
import type { Feature } from '@shared/types/model/featureModel'
import type { ProjectModel } from '@shared/types/model/projectModel'
import { buildFeatureHandoff } from '@core/handoff/buildFeatureHandoff'
import { loadFeatureDelivery } from '../../lib/loadFeatureDelivery'
import { serializeScreenToSvg } from '@core/export/svgSerializer'
import { StructurePreview } from '../project/StructurePreview'

type Section = 'overview' | 'pages' | 'states' | 'components' | 'responsive' | 'interactions' | 'changes' | 'notes' | 'source'
const sections: Section[] = ['overview', 'pages', 'states', 'components', 'responsive', 'interactions', 'changes', 'notes', 'source']

export function FeatureHandoffPanel({ projectId, feature, projectModel, onReturnToDesign, onOpenPage, onOpenComponents }: { projectId: string; feature: Feature; projectModel: ProjectModel; onReturnToDesign: () => void; onOpenPage: (pageRef: import('@shared/types/model/featureModel').PageRef, stateId: string | null) => void; onOpenComponents: () => void }) {
  const [handoff, setHandoff] = useState<FeatureHandoff | null>(null)
  const [delivery, setDelivery] = useState<HandoffInput | null>(null)
  const [section, setSection] = useState<Section>('overview')
  const [technicalId, setTechnicalId] = useState<string | null>(null)
  const [inspectedPageId, setInspectedPageId] = useState<string | null>(null)
  const [inspectMode, setInspectMode] = useState<'current' | 'proposed' | 'compare'>('proposed')
  const [inspectViewport, setInspectViewport] = useState<Breakpoint>('desktop')
  useEffect(() => { let live = true; void loadFeatureDelivery(projectId, feature, projectModel).then((data) => { if (live) { setDelivery(data); setHandoff(buildFeatureHandoff(data)) } }); return () => { live = false } }, [projectId, feature, projectModel])
  const eligible = feature.status === 'approved' || feature.status === 'ready-for-development'
  if (!eligible) return <Empty title="Handoff becomes available when this Feature is Approved or Ready for Development." action={onReturnToDesign} />
  if (!handoff) return <Empty title="Preparing handoff from the approved Feature…" />
  return (
    <div className="flex h-full min-h-0 bg-bg">
      <aside className="w-52 shrink-0 border-r border-border bg-bg-raised p-3">
        <div className="mb-3 px-2 text-[11px] font-semibold tracking-wider text-text-3">Handoff</div>
        {sections.map((item) => <button key={item} type="button" onClick={() => setSection(item)} className={`mb-0.5 w-full rounded-md px-2.5 py-2 text-left text-[12px] font-medium capitalize ${section === item ? 'bg-selected text-accent-2' : 'text-text-2 hover:bg-hover'}`}>{item}</button>)}
        <button type="button" onClick={onReturnToDesign} className="mt-5 w-full rounded-lg border border-border px-2.5 py-2 text-[11.5px] font-semibold text-text-2">Return to Design</button>
      </aside>
      <main className="flex-1 overflow-y-auto p-4">
        <div className="mx-auto max-w-5xl">
          <div className="mb-3"><div className="text-[11px] font-semibold tracking-widest text-accent-2">Developer specification</div><h1 className="mt-1 text-[13px] font-semibold text-text">{feature.name}</h1><p className="mt-1 max-w-2xl text-[12.5px] leading-relaxed text-text-2">{feature.description || 'No feature description provided.'}</p></div>
          {section === 'overview' && <Overview handoff={handoff} />}
          {section === 'pages' && <>{inspectedPageId && delivery && <ApprovedPagePreview page={handoff.pages.find((page) => page.ref.pageId === inspectedPageId)!} delivery={delivery} mode={inspectMode} viewport={inspectViewport} onMode={setInspectMode} onViewport={setInspectViewport} onClose={() => setInspectedPageId(null)} />}<Cards>{handoff.pages.map((page) => <Card key={`${page.ref.kind}:${page.ref.pageId}`} title={page.name} badge={page.kind}><Line label="Route" value={page.route ?? 'No route specified'} /><Line label="States" value={page.states.map((state) => state.name).join(', ') || 'None'} /><Line label="Responsive" value={page.responsive.length ? `${page.responsive.length} explicit overrides` : 'Inherits desktop'} /><Line label="Components" value={String(page.componentIds.length)} /><div className="mt-2 flex gap-3"><button type="button" onClick={() => { setInspectedPageId(page.ref.pageId); setInspectMode(page.kind === 'new' ? 'proposed' : 'compare') }} className="text-[11px] font-semibold text-accent-2">Inspect handoff</button><button type="button" onClick={() => onOpenPage(page.ref, page.states[0]?.id ?? null)} className="text-[11px] font-semibold text-text-3">Open in Design</button></div></Card>)}</Cards></>}
          {section === 'states' && <Cards>{handoff.pages.flatMap((page) => page.states.map((state) => <Card key={state.id} title={`${page.name} / ${state.name}`} badge={state.origin}><Line label="Viewports" value={state.viewport.join(', ')} /><Line label="Differences" value={state.differences.join('; ') || 'No semantic changes recorded'} /><Line label="Interactions" value={state.interactions.join('; ') || 'None'} /><Line label="Notes" value={String(state.notes.length)} /></Card>))}</Cards>}
          {section === 'components' && <div className="space-y-6">{(['reused', 'modified', 'new'] as const).map((kind) => <div key={kind}><h2 className="mb-2 text-[12px] font-semibold tracking-wide text-text-3">{kind === 'reused' ? 'Existing Components Reused' : kind === 'modified' ? 'Existing Components Modified' : 'New Components Required'}</h2><Cards>{handoff.components.filter((item) => item.kind === kind).map((component) => <Card key={component.id} title={component.name} badge={component.kind}><Line label="Used" value={`${component.usageCount} times · ${component.pageNames.join(', ') || 'No page instance found'}`} /><Line label="Source" value={component.sourcePath ?? 'New component, no source yet'} /><Line label="Variants" value={component.variants.join(', ') || 'None recorded'} /><Line label="Properties" value={component.props.map((prop) => `${prop.name}: ${prop.type}`).join(', ') || 'None detected'} /><Line label="Changes" value={component.changes.join('; ') || 'No Feature-specific changes'} /><button type="button" onClick={onOpenComponents} className="mt-2 text-[11px] font-semibold text-accent-2">Open component</button></Card>)}</Cards></div>)}</div>}
          {section === 'responsive' && <Cards>{handoff.pages.map((page) => <Card key={page.name} title={page.name}><Line label="Desktop" value="Base design" />{page.responsive.map((item) => <Line key={`${item.nodeId}:${item.breakpoint}`} label={`${item.breakpoint} · ${item.nodeName}`} value={Object.entries(item.override).map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join(' · ')} />)}{!page.responsive.length && <Line label="Tablet / Mobile" value="No explicit overrides; inherits desktop" />}</Card>)}</Cards>}
          {section === 'interactions' && <Cards>{handoff.interactions.map((item) => <Card key={item.id} title={item.label || item.trigger} badge={item.journeyName}><Line label="Trigger" value={item.trigger} /><Line label="Element" value={item.element} /><Line label="From" value={item.from} /><Line label="To" value={item.to} /></Card>)}</Cards>}
          {section === 'changes' && <Cards>{handoff.changes.map((item) => <Card key={`${item.id}:${item.technical.revisionId}`} title={item.description} badge={item.pageName}><Line label="Element" value={item.element} /><button type="button" className="mt-2 text-[11px] font-semibold text-accent-2" onClick={() => setTechnicalId(technicalId === item.technical.revisionId ? null : item.technical.revisionId)}>{technicalId === item.technical.revisionId ? 'Hide' : 'Inspect'} technical details</button>{technicalId === item.technical.revisionId && <pre className="mt-2 overflow-auto rounded bg-bg p-3 text-[11px] text-text-2">{JSON.stringify(item.technical, null, 2)}</pre>}</Card>)}</Cards>}
          {section === 'notes' && <Cards>{handoff.notes.map((note) => <Card key={note.id} title={note.elementLabel ?? 'Design note'} badge={note.priority}><p className="text-[12px] leading-relaxed text-text-2">{note.comment}</p><Line label="Status" value={note.status} /></Card>)}</Cards>}
          {section === 'source' && <Cards>{handoff.pages.filter((page) => page.sourcePath).map((page) => <Card key={page.name} title={page.name} badge="Page"><Line label="Source" value={page.sourcePath!} /><Line label="Route" value={page.route ?? 'Unknown'} /></Card>)}{handoff.components.map((component) => <Card key={component.id} title={component.name} badge="Component"><Line label="Source" value={component.sourcePath ?? 'New component, no source yet'} /></Card>)}</Cards>}
        </div>
      </main>
    </div>
  )
}

function Overview({ handoff }: { handoff: FeatureHandoff }) { const entries = useMemo(() => [['Pages', handoff.summary.pages], ['Changed Pages', handoff.summary.changedPages], ['New Pages', handoff.summary.newPages], ['Reference Pages', handoff.summary.referencePages], ['States', handoff.summary.states], ['Responsive Views', handoff.summary.responsiveViews], ['Existing Components Reused', handoff.summary.reusedComponents], ['Existing Components Modified', handoff.summary.modifiedComponents], ['New Components', handoff.summary.newComponents], ['Journey Steps', handoff.summary.journeySteps], ['Annotations', handoff.summary.annotations]], [handoff]); return <><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{entries.map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-panel p-3"><div className="text-[13px] font-semibold text-text">{value}</div><div className="text-[11px] text-text-3">{label}</div></div>)}</div><div className="mt-5 rounded-xl border border-border bg-panel p-4"><Line label="Status" value={handoff.feature.status.replaceAll('-', ' ')} /><Line label="Design version" value={handoff.approvedVersion?.name ?? 'Approved working design'} /><Line label="What to implement" value={handoff.changes.map((item) => item.description).join('; ') || 'Implement the approved proposed designs, states and interactions listed in this handoff.'} /></div></> }
function Cards({ children }: { children: React.ReactNode }) { return <div className="grid gap-3 lg:grid-cols-2">{children}</div> }
function Card({ title, badge, children }: { title: string; badge?: string; children: React.ReactNode }) { return <article className="rounded-xl border border-border bg-panel p-4"><div className="mb-3 flex items-start justify-between gap-3"><h2 className="text-[13px] font-semibold text-text">{title}</h2>{badge && <span className="rounded-md bg-selected px-2 py-0.5 text-[11px] font-semibold tracking-wide text-accent-2">{badge}</span>}</div>{children}</article> }
function Line({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[110px_1fr] gap-3 border-t border-border/60 py-2 first:border-0"><span className="text-[11px] font-semibold text-text-3">{label}</span><span className="break-words text-[11.5px] leading-relaxed text-text-2">{value}</span></div> }
function Empty({ title, action }: { title: string; action?: () => void }) { return <div className="flex h-full items-center justify-center p-4 text-center"><div><p className="text-[13px] text-text-2">{title}</p>{action && <button type="button" onClick={action} className="mt-3 text-[12px] font-semibold text-accent-2">Return to Design</button>}</div></div> }

function ApprovedPagePreview({ page, delivery, mode, viewport, onMode, onViewport, onClose }: { page: FeatureHandoff['pages'][number]; delivery: HandoffInput; mode: 'current' | 'proposed' | 'compare'; viewport: Breakpoint; onMode: (mode: 'current' | 'proposed' | 'compare') => void; onViewport: (viewport: Breakpoint) => void; onClose: () => void }) {
  const state = page.states[0]
  const tree = state ? delivery.trees[state.id] : null
  const current = page.ref.kind === 'existing' ? delivery.projectModel.pages.find((item) => item.id === page.ref.pageId) : null
  const width = viewport === 'desktop' ? 1440 : viewport === 'tablet' ? 768 : 390
  const proposed = tree ? serializeScreenToSvg(tree, viewport, width, { includeMetadata: false, name: `${page.name} approved design` }).svg : null
  const modes = page.kind === 'new' ? ['proposed'] as const : ['current', 'proposed', 'compare'] as const
  return <section className="mb-5 rounded-xl border border-accent/30 bg-panel p-4"><div className="mb-3 flex items-center justify-between"><div><div className="text-[13px] font-semibold text-text">{page.name}</div><div className="text-[11px] text-text-3">Approved Feature projection · read-only</div></div><button type="button" onClick={onClose} className="text-[11px] text-text-3">Close</button></div><div className="mb-3 flex justify-between"><div className="flex gap-1">{modes.map((item) => <button key={item} type="button" onClick={() => onMode(item)} className={`rounded px-2 py-1 text-[11px] font-semibold capitalize ${mode === item ? 'bg-selected text-accent-2' : 'text-text-3'}`}>{item}</button>)}</div><div className="flex gap-1">{(['desktop', 'tablet', 'mobile'] as Breakpoint[]).map((item) => <button key={item} type="button" onClick={() => onViewport(item)} className={`rounded px-2 py-1 text-[11px] font-semibold capitalize ${viewport === item ? 'bg-selected text-accent-2' : 'text-text-3'}`}>{item}</button>)}</div></div><div className={`grid max-h-[440px] gap-3 overflow-auto rounded-lg bg-bg p-3 ${mode === 'compare' ? 'grid-cols-2' : 'grid-cols-1'}`}>{(mode === 'current' || mode === 'compare') && <div><div className="mb-1 text-[11px] font-semibold text-text-3">Current</div><div className="min-h-48 overflow-hidden rounded bg-panel"><StructurePreview structure={current?.structure ?? []}/></div></div>}{(mode === 'proposed' || mode === 'compare') && <div><div className="mb-1 text-[11px] font-semibold text-text-3">Proposed</div>{proposed ? <div className="overflow-hidden rounded" dangerouslySetInnerHTML={{ __html: proposed }} /> : <div className="p-4 text-center text-[11px] text-text-3">No approved design tree for this page.</div>}</div>}</div></section>
}
